[package]
name = "pkg-dev"
version = "0.1.0"

[dependencies]
lazy_static = "1.0"

[dev-dependencies.pkg-lib]
version = "0.1.0"
path = "../pkg-lib"

[build-dependencies.pkg-build]
version = "0.1.0"
path = "../pkg-build"