[workspace]
members = [
  "pkg-sys",
  "pkg-build",
  "pkg-lib",
  "pkg-bin",
  'pkg-dev',
]

[package]
name = "pkg-all"
version = "0.1.0"

[dependencies]
pkg-lib = { version = "0.1.0", path = "./pkg-lib" }

[dependencies.pkg-bin]
version = "0.1.0"
path = "./pkg-bin"
